# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'the skills  of RAC' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for the skills  of RAC
pod ‘ReactiveCocoa’
end
