# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Lianxi' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Lianxi

pod 'ReactiveCocoa', '~> 4.1.0'

end
